config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products
  end

  namespace :user do
    resources :products, only: [:index, :show]
  end

  namespace :api do
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :bigint           not null, primary key
#  description    :text
#  name           :string
#  price_currency :string
#  price_subunit  :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Product < ApplicationRecord
  def as_json
    { 
      name: name, 
      description: description, 
      price_currency: price_currency, 
      price_subunit: price_subunit
    }
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products or /products.json
  def index
    @products = Product.all.order(:id)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(id: @product.id), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(id: @product.id), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price_subunit, :price_currency)
    end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  
end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products or /products.json
  def index
    @products = Product.all

    render json: { success: true, products: @products.map(&:as_json)}
  end

  # GET /products/1 or /products/1.json
  def show
    render json: { success: true, product: @product.as_json}
  end

  # GET /products/new
  def new
    @product = Product.new
    render json: { success: true, product: @product.as_json}
  end

  # GET /products/1/edit
  def edit
    render json: { success: true, product: @product.as_json}
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        render json: { success: true, product: @product.as_json}
      else
        render json: { errors: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        render json: { success: true, product: @product.as_json}
      else
        render json: { errors: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      render json: { success: true }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price_subunit, :price_currency)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price_subunit, :price_currency)
    end
end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController

end

app/controllers/user/products_controller.rb
class User::ProductsController < User::ApplicationController
  # GET /products or /products.json
  def index
    @products = Product.all.order(:id)
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with model: product, url: product.new_record? ? admin_products_path : admin_product_path(id: product.id), method: product.new_record? ? "POST" : "PATCH", class: "max-w-md mx-auto p-6" do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid grid-cols-2 mb-4">
    <%= form.label :name, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="grid grid-cols-2 mb-4">
    <%= form.label :description, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="grid grid-cols-2 mb-4">
    <%= form.label :price_subunit, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :price_subunit, class: "w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="grid grid-cols-2 mb-4">
    <%= form.label :price_currency, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :price_currency, class: "w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="flex justify-center">
    <%= link_to "Back to products", admin_products_path, class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
    <%= form.submit class: "bg-emerald-300 hover:bg-emerald-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="container max-width">
  <div class="grid grid-cols-2 mb-4">
    <div class="text-2xl font-bold">Edit Products</div>
  </div>

  <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
    <%= render "form", product: @product %>
  </div>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container max-width">
  <div class="grid grid-cols-2 mb-4">
    <div class="text-2xl font-bold">Products</div>
    <div class="justify-self-end">
      <%= link_to "New product", new_admin_product_path, class: "bg-emerald-300 hover:bg-emerald-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
    </div>
  </div>

  <% @products.each do |product| %>
    <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
      <%= render product %>
      <div class="flex justify-center">
        <%= link_to "Show this product", admin_product_path(id: product.id), class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
        <%= link_to "Edit this product", edit_admin_product_path(id: product.id), class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/products/new.html.erb
<div class="container max-width">
  <div class="grid grid-cols-2 mb-4">
    <div class="text-2xl font-bold">New Products</div>
  </div>

  <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
    <%= render "form", product: @product %>
  </div>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container max-width">
  <div class="grid grid-cols-2 mb-4">
    <div class="text-2xl font-bold"><%= @product.name %></div>
    <div class="grid justify-self-end">
    <%= link_to "Edit this product", edit_admin_product_path(id: @product.id), class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
    </div>
  </div>

  <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
    <%= render "product", product: @product %>
  </div>

  <div class="flex justify-center">
    <%= link_to "Back to products", admin_products_path, class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
    <%= link_to "Delete this product", admin_product_path(id: @product.id), data: { "turbo-method": :delete }, method: :delete, class: "text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpellBookTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price_subunit, style: "display: block" %>
    <%= form.number_field :price_subunit %>
  </div>

  <div>
    <%= form.label :price_currency, style: "display: block" %>
    <%= form.text_field :price_currency %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/user/products/_product.html.erb
  <div class="mb-4">
    <div class="font-bold">Name:</div>
    <div><%= product.name %></div>
  </div>

  <div class="mb-4">
    <div class="font-bold">Description:</div>
    <div><%= product.description %></div>
  </div>

  <div class="mb-4">
    <div class="font-bold">Price subunit:</div>
    <div><%= product.price_subunit %></div>
  </div>

  <div class="mb-4">
    <div class="font-bold">Price currency:</div>
    <div><%= product.price_currency %></div>
  </div>

app/views/user/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container max-width">
  <div class="text-2xl font-bold mb-4">Products</div>

  <% @products.each do |product| %>
    <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
      <%= render product %>
      <div class="flex justify-center">
        <%= link_to "Show this product", user_product_path(id: product.id), class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
      </div>
    </div>
  <% end %>
</div>

app/views/user/products/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container max-width">
  <div class="text-2xl font-bold mb-4"><%= @product.name %></div>

  <div class="block max-w p-6 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
    <%= render "product", product: @product %>
  </div>

  <div class="flex justify-center">
    <%= link_to "Back to products", user_products_path, class: "bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none" %>
  </div>
</div>